/// Flutter icons Fragged
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Fragged
///      fonts:
///       - asset: fonts/Fragged.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Fragged {
  Fragged._();

  static const _kFontFam = 'Fragged';
  static const String? _kFontPkg = null;

  static const IconData fragged = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class Patreon {
  Patreon._();

  static const _kFontFam = 'Patreon';
  static const String? _kFontPkg = null;

  static const IconData patreon_logo = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class Github {
  Github._();

  static const _kFontFam = 'Github';
  static const String? _kFontPkg = null;

  static const IconData github = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}