/// Flutter icons Fragged
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Fragged
///      fonts:
///       - asset: fonts/Fragged.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Logos {
  Logos._();

  static const _kFontFam = 'Logos';
  static const String? _kFontPkg = null;

  static const IconData patreon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fragged = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discord = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}


class SheetIcons {
  SheetIcons._();

  static const _kFontFam = 'SheetIcons';
  static const String? _kFontPkg = null;

  static const IconData enemy = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}